from enum import Enum


class SanitisationTypes(Enum):
    NONE = 0

    WHITESPACE = 1
    DIGIT = 2
    NEWLINE = 3
    UNDERSCORE = 4

    APOSTROPHE = 10

    STRUCTURED_WHITESPACE = 20
    STRUCTURED_PERIOD_SPACE = 21

    STRUCTURED_FRONTMATTER = 30
    STRUCTURED_CALLOUT = 31

    STRUCTURED_MARKDOWN_INTERNAL_LINK = 31
    STRUCTURED_MARKDOWN_EXTERNAL_LINK = 32

    STRUCTURED_RAWHTML = 33
