EMPTY = ""
SPACE = " "
NEWLINE = "\n"
SLASH = "/"
PERIOD = "."
BAR = "|"
COMMA = ","
ASTERISK = "*"
EXCLAMATION = "!"

OPEN_SQUARE_BRACKET_PAIR = "[["
CLOSE_SQUARE_BRACKET_PAIR = "]]"

OPEN_SQUARE_BRACKET = "["
MIDDLE_BRACKET_PAIR = "]("
CLOSE_BRACKET = ")"
CLOSE_SQUARE_BRACKET = "]"

OPEN_CALLOUT = "> [!"
CLOSE_CALLOUT = CLOSE_SQUARE_BRACKET

SVG = "<svg"
LT = "<"

TRIDASH = "---"

FRONTMATTER = TRIDASH
FRONTMATTER_CLOSE = f"{NEWLINE}{TRIDASH}"
